---
- hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      register: update_result

    - name: Perform package upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: update_result.changed